services:
  bas-scanner:
    env_file:
      - ./scanner.env
      - ./key.env
    build: .
    container_name: bas-scanner
    hostname: bas-scanner
    network_mode: "host"

  # redis:
  #   image: redislabs/redismod
  #   container_name: redis
  #   ports:
  #     - 6379 : 6379
